FROM ubuntu:20.04

RUN apt-get update
RUN apt-get install -y git
RUN apt-get install -y curl

RUN curl -sL https://deb.nodesource.com/setup_18.x | bash
RUN apt-get install -y nodejs

RUN npm install -g pm2
RUN npm install -g typescript@4.7.4
RUN npm install -g ts-node@10.9.1

WORKDIR /data
WORKDIR /usr/src/app

COPY ["./package.json","./tsconfig.json","./src","./"]

# RUN git clone https://github.com/vechain/rosetta.git
# WORKDIR /usr/src/app/rosetta
# RUN git checkout master
# RUN npm ci && npm run build

# RUN npm install -g pm2

# COPY --from=builder /go/thor/bin/thor /usr/src/app/
# EXPOSE 8080 8669 11235 11235/udp

# ENTRYPOINT ["sh","./start.sh"]
